[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "transcript-extractor"
version = "0.1.0"
description = "YouTube transcript extractor with command-line interface"
readme = "README.md"
requires-python = ">=3.8"
license = {file = "LICENSE"}
authors = [
    {name = "User", email = "user@example.com"},
]
keywords = ["youtube", "transcript", "extractor", "cli"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Topic :: Multimedia :: Video",
    "Topic :: Text Processing",
]

dependencies = [
    "youtube-transcript-api>=0.6.0",
    "requests>=2.25.0",
]

[project.scripts]
transcript-extractor = "transcript_extractor.cli:main"

[project.optional-dependencies]
dev = [
    "pytest>=7.0.0",
    "pytest-cov>=4.0.0",
    "black>=22.0.0",
    "isort>=5.10.0",
    "flake8>=4.0.0",
    "mypy>=0.950",
]

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"]
python_functions = ["test_*"]
addopts = [
    "--cov=transcript_extractor",
    "--cov-report=html",
    "--cov-report=term-missing",
    "--strict-markers",
    "-v"
]

[project.urls]
Homepage = "https://github.com/mwalker-tmd/YouTubeTranscriptExtractor"
Repository = "https://github.com/mwalker-tmd/YouTubeTranscriptExtractor"
Issues = "https://github.com/mwalker-tmd/YouTubeTranscriptExtractor/issues"

[tool.black]
line-length = 88
target-version = ['py38']
include = '\.pyi?$'
extend-exclude = '''
/(
  # directories
  \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | build
  | dist
)/
'''

[tool.isort]
profile = "black"
multi_line_output = 3
line_length = 88

[tool.mypy]
python_version = "3.8"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true 